/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ORzPC6RgGrw
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-[#f3f4f6]">
      <div className="container mx-auto px-4 md:px-6 lg:px-8">
        <div className="flex flex-col items-center text-center">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900">Welcome to Our Platform</h1>
          <p className="mt-4 text-xl md:text-2xl text-gray-600 max-w-2xl mx-auto">
            We&apos;re excited to have you here! Subscribe to our newsletter to stay updated with our latest news and
            updates.
          </p>
          <div className="mt-8 w-full max-w-md mx-auto">
            <form className="flex items-center space-x-4">
              <Input
                className="flex-grow px-4 py-2 border border-gray-300 rounded-md"
                placeholder="Enter your email"
                type="email"
              />
              <Button className="px-6 py-2 text-white bg-blue-600 rounded-md" type="submit">
                Subscribe
              </Button>
            </form>
          </div>
          <p className="mt-4 text-sm text-gray-500">
            By subscribing, you agree to our
            <Link className="underline text-blue-600" href="#">
              Terms & Conditions
            </Link>
            .{"\n              "}
          </p>
        </div>
      </div>
    </section>
  )
}
